# Form implementation generated from reading ui file 'e:\Projects\text_game\src\ui\pyqt\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 639)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("e:\\Projects\\text_game\\src\\ui\\pyqt\\../../../images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputField = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.inputField.setFont(font)
        self.inputField.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.inputField.setAutoFillBackground(True)
        self.inputField.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.inputField.setInputMask("")
        self.inputField.setText("")
        self.inputField.setMaxLength(32767)
        self.inputField.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.inputField.setDragEnabled(False)
        self.inputField.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.inputField.setClearButtonEnabled(False)
        self.inputField.setObjectName("inputField")
        self.verticalLayout.addWidget(self.inputField)
        self.executeButton = QtWidgets.QPushButton(self.centralwidget)
        self.executeButton.setCheckable(False)
        self.executeButton.setChecked(False)
        self.executeButton.setObjectName("executeButton")
        self.verticalLayout.addWidget(self.executeButton)
        self.outputField = QtWidgets.QTextBrowser(self.centralwidget)
        self.outputField.setObjectName("outputField")
        self.verticalLayout.addWidget(self.outputField)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Game"))
        self.inputField.setPlaceholderText(_translate("MainWindow", "Введите команду"))
        self.executeButton.setText(_translate("MainWindow", "Исполнить команду"))
        self.outputField.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Trebuchet MS\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
